countries_data = [
    {"country": "Nigeria", "languages": ["English", "Hausa", "Yoruba", "Igbo"]},
    {"country": "United States", "languages": ["English", "Spanish"]},
    {"country": "Germany", "languages": ["German"]},
    {"country": "France", "languages": ["French"]},
    {"country": "India", "languages": ["Hindi", "English", "Bengali", "Tamil"]},
    {"country": "Brazil", "languages": ["Portuguese"]},
    {"country": "China", "languages": ["Mandarin", "Cantonese"]},
    {"country": "Russia", "languages": ["Russian"]},
    {"country": "Canada", "languages": ["English", "French"]},
    {"country": "South Africa", "languages": ["Zulu", "Xhosa", "Afrikaans", "English"]},
    {"country": "Switzerland", "languages": ["German", "French", "Italian", "Romansh"]},
    {"country": "Mexico", "languages": ["Spanish"]},
    {"country": "Argentina", "languages": ["Spanish"]},
    {"country": "Egypt", "languages": ["Arabic"]},
    {"country": "Japan", "languages": ["Japanese"]},
    {"country": "Turkey", "languages": ["Turkish"]},
    {"country": "Spain", "languages": ["Spanish", "Catalan", "Galician", "Basque"]},
    {"country": "Pakistan", "languages": ["Urdu", "English", "Punjabi", "Sindhi"]},
]
